name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Install gh-pages
        run: yarn global add gh-pages

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GH_PAGES_TOKEN: ${{ github.actor }}:${{ secrets.GH_PAGES_TOKEN }}
        run: |
          git config --global user.email "danicolms@icloud.com"
          git config --global user.name "danicolms"
          git checkout gh-pages
          cp -r dist/* .
          git add .
          git commit -m "Deploy changes"
          git push --quiet origin gh-pages
